#######################
# Auto-configure the Cacophony module
#######################

name: caco
ckpt: Cacophony.ckpt
model:
  _target_: embedding.CacoModel
  # Enable fusion if "fusion" is present in the checkpoint
  enable_fusion: false
  # Set the audio model based on the presence of "630k" in the checkpoint
  amodel: HTSAT-tiny
  # Set the text model. Options: ["roberta"]
  tmodel: roberta
  # Checkpoint path
  ckpt_path: ${general.ckpt_path}
  # Model device
  device: ${system.device}
